title: drifty repacks
description: All driftywinds releases
social_link: twitter
social_username: driftywinds
github_repo: drifty_repacks
github_username: driftywinds
theme_color: black
remote_theme: internet-de-france/swiss
baseurl: /drifty_repacks
defaults:
  - scope:
      path: ''
      type: pages
    values:
      category_name: ''
  - scope:
      path: ''
      type: posts
    values:
      categories: ''
remote_theme_layouts:
  - ''
  - default
  - page
  - post
  - home
  - category_index
social_links:
  - twitter
  - instagram
  - medium
  - dribbble
theme_colors:
  - black
  - blue
  - gray
  - magenta
  - orange
  - red
  - white
  - yellow
